ARG NODE_VERSION=20.12.0

FROM node:${NODE_VERSION}-slim AS build

WORKDIR /app

COPY ./nuxtjs/package.json /app/
COPY ./nuxtjs/package-lock.json /app/

RUN npm install

COPY ./nuxtjs/ ./

RUN npm run build

FROM node:${NODE_VERSION}-slim

WORKDIR /app

COPY --from=build ./app/.output/ ./

ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["node","/app/server/index.mjs"]
